# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=['C:\\watch_folder_hires_70'],
    binaries=[],
    datas=[
        # Tambahkan file konfigurasi default jika ada
        # ('config.json', '.'),
    ],
    hiddenimports=[
        # Import yang mungkin tidak terdeteksi otomatis
        'tkinter',
        'threading',
        'queue',
        'datetime',
        'time',
        'os',
        'sys',
        'json',
        'logging',
        'shutil',
        're',
        'src.constants.settings',
        'src.models.file_job',
        'src.models.settings',
        'src.models.upload_job',
        'src.utils.logger',
        'src.utils.config_manager',
        'src.utils.state_manager',
        'src.utils.history',
        'src.utils.validators',
        'src.core.file_handler',
        'src.core.queue_manager',
        'src.core.download_worker',
        'src.core.download_manager',
        'src.core.upload_worker_51',
        'src.core.upload_worker_40',
        'src.core.upload_queue_manager',
        'src.core.upload_manager',
        'src.core.upload_controller',
        'src.core.file_monitor',
        'src.gui.queue_panel',
        'src.gui.progress_panel',
        'src.gui.log_panel',
        'src.gui.history_panel',
        'src.gui.upload_panel_51',
        'src.gui.upload_panel_40',
        'src.gui.settings_window',
        'src.gui.main_window',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='WatchFolderHires70',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # <-- False karena GUI (tkinter), True jika ingin console
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=icon.ico  # Bisa tambahkan icon: 'icon.ico'
)